name: CI

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    runs-on: windows-2019
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild BIDebugEngine\BIDebugEngine.sln

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BIDebugEngine
          path: |
            BIDebugEngine/**/Release/BIDebugEngine*.dll
            BIDebugEngine/**/Release/BIDebugEngine*.pdb
          if-no-files-found: error
